import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Providers from "@/components/Provider";

// react toast 
import {Toaster} from 'react-hot-toast'

const inter = Inter({ subsets: ["latin"] });
import { GeistSans } from  "geist/font/sans"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <html suppressHydrationWarning={true}  className={`${GeistSans.variable} `} lang="en">
          <body >{children}</body>
        <Toaster />
        </html>
      </Providers>
    </ClerkProvider>
  );
}
